-- 코드를 입력하세요
SELECT
    CAR_ID,
    -- AVG(END_DATE - START_DATE) AS AVERAGE_DURATION
    -- 그냥 - 연산자 쓰면 2022-10-05 와 2022-09-05의 차이를 100이라고 함
    ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING 
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC;







