-- 코드를 작성해주세요

SELECT
    E.ID
    ,CASE
        WHEN E.SIZE_OF_COLONY <= 100
        THEN 'LOW'
        WHEN E.SIZE_OF_COLONY BETWEEN 101 AND 1000
        THEN 'MEDIUM'
        WHEN E.SIZE_OF_COLONY > 1000
        THEN 'HIGH'
    END AS SIZE
FROM
    ECOLI_DATA AS E
ORDER BY
    E.ID
