-- 코드를 입력하세요
SELECT
    CASE
    WHEN PRICE < 10000
    THEN 0
    ELSE CONCAT(SUBSTR(PRICE/10000,1,1),'0000')
    END AS PRICE_GROUP
    ,COUNT(*) AS PRODUCTS
FROM
    PRODUCT
GROUP BY
    PRICE_GROUP
ORDER BY
    PRICE_GROUP