-- 코드를 입력하세요
SELECT
    M.MEMBER_NAME
    ,R.REVIEW_TEXT
    ,DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE AS M
    JOIN
    REST_REVIEW AS R
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE
    M.MEMBER_ID = 
    (SELECT
        M.MEMBER_ID
    FROM
        MEMBER_PROFILE AS M
        JOIN
        REST_REVIEW AS R
        ON M.MEMBER_ID = R.MEMBER_ID
    GROUP BY
        M.MEMBER_NAME
    ORDER BY
        COUNT(*) DESC
    LIMIT 1)
ORDER BY
    R.REVIEW_DATE
    ,R.REVIEW_TEXT