-- 코드를 입력하세요
SELECT
    INGREDIENT_TYPE
    ,SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    ICECREAM_INFO AS I
    JOIN
    FIRST_HALF AS F
    ON I.FLAVOR = F.FLAVOR
GROUP BY
    INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER;